name: Continuous Integration

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: volta-cli/action@v4

            - run: yarn install
            - run: yarn build
            - name: Run Tests
              run: yarn test
            - name: Lint Code
              run: yarn lint
